allowBuilds:
  esbuild: true
  sharp: true
  workerd: true

linkWorkspacePackages: false

packages:
  - .
  - packages/*

minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - cantraceviewer
patchedDependencies:
  svelte-check@4.7.1: patches/svelte-check@4.7.1.patch
